name: API Key Check Module

on:
  workflow_call:

jobs:
  check-api-keys:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Check NANO_BANANA_EDIT API Key
      env:
        NANO_BANANA_EDIT: ${{ secrets.NANO_BANANA_EDIT }}
      run: |
        if [ -z "$NANO_BANANA_EDIT" ]; then
          echo "❌ NANO_BANANA_EDIT API key is not set"
          exit 1
        else
          echo "✅ NANO_BANANA_EDIT API key is configured"
          echo "Key format: ${NANO_BANANA_EDIT:0:8}..."
        fi
        
    - name: Check CLAUDE_CODE_OAUTH_TOKEN
      env:
        CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
      run: |
        if [ -z "$CLAUDE_CODE_OAUTH_TOKEN" ]; then
          echo "❌ CLAUDE_CODE_OAUTH_TOKEN is not set"
          exit 1
        else
          echo "✅ CLAUDE_CODE_OAUTH_TOKEN is configured"
          echo "Token format: ${CLAUDE_CODE_OAUTH_TOKEN:0:8}..."
        fi
        
    - name: Validate NANO_BANANA_EDIT URL Format
      env:
        NANO_BANANA_EDIT: ${{ secrets.NANO_BANANA_EDIT }}
      run: |
        if [[ "$NANO_BANANA_EDIT" == https://kamui-code.ai* ]]; then
          echo "✅ NANO_BANANA_EDIT URL format is correct for Kamui Code MCP"
        else
          echo "❌ NANO_BANANA_EDIT should be Kamui Code MCP URL, got: ${NANO_BANANA_EDIT:0:20}..."
          exit 1
        fi
        
    - name: Summary
      if: success()
      run: |
        echo "🎉 All API keys are properly configured and accessible!"
        echo "Ready for automated content generation."