name: API Key Check Module

on:
  workflow_call:

jobs:
  check-api-keys:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Check QWEN_IMAGE API Key
      env:
        QWEN_IMAGE: ${{ secrets.QWEN_IMAGE }}
      run: |
        if [ -z "$QWEN_IMAGE" ]; then
          echo "❌ QWEN_IMAGE API key is not set"
          exit 1
        else
          echo "✅ QWEN_IMAGE API key is configured"
          echo "Key format: ${QWEN_IMAGE:0:8}..."
        fi
        
    - name: Check CLAUDE_CODE_OAUTH_TOKEN
      env:
        CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
      run: |
        if [ -z "$CLAUDE_CODE_OAUTH_TOKEN" ]; then
          echo "❌ CLAUDE_CODE_OAUTH_TOKEN is not set"
          exit 1
        else
          echo "✅ CLAUDE_CODE_OAUTH_TOKEN is configured"
          echo "Token format: ${CLAUDE_CODE_OAUTH_TOKEN:0:8}..."
        fi
        
    - name: Validate QWEN Image URL Format
      env:
        QWEN_IMAGE: ${{ secrets.QWEN_IMAGE }}
      run: |
        if [[ "$QWEN_IMAGE" == https://kamui-code.ai* ]]; then
          echo "✅ QWEN_IMAGE URL format is correct for Kamui Code MCP"
        else
          echo "❌ QWEN_IMAGE should be Kamui Code MCP URL, got: ${QWEN_IMAGE:0:20}..."
          exit 1
        fi
        
    - name: Summary
      if: success()
      run: |
        echo "🎉 All API keys are properly configured and accessible!"
        echo "Ready for automated content generation."